version: "3.9"

services:
  svs-app:
    build:
      context: ./frontend
    container_name: svs-app
    restart: unless-stopped
    expose:
      - 80
    networks:
      - web
    environment:
      - VIRTUAL_HOST=svs-frontend.model-technologie.com
      - LETSENCRYPT_HOST=svs-frontend.model-technologie.com
      - LETSENCRYPT_EMAIL=business.modeltech@gmail.com

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    labels:
      - com.github.nginx-proxy.nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - web

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: "business.modeltech@gmail.com"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - web

networks:
  web:
    external: false

volumes:
  certs:
  vhost:
  html:
  acme:

